name: Measure black bars
on:
  issue_comment:
    types: [created]
jobs:
  custom-game-area:
    if: >-
      github.event.issue.number == 1347 &&
      (contains(github.event.comment.body, '.png') ||
      contains(github.event.comment.body, '.jpeg') ||
      contains(github.event.comment.body, '.jpg'))
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fate-grand-automata/custom-game-area
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Measure black bars
        shell: bash
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          cd /app
          url=$(echo "$BODY" | grep -Eo 'http(s)?://[^ >]+?\.(png|jpeg|jpg)')
          curl $url --output /app/image.jpg --fail
          echo "COMMENT=@${{ github.event.comment.user.login }} Your offsets are $(python custom-game-area.py)" >> $GITHUB_ENV
          echo "Comment: ${{ env.COMMENT }}"
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v2
        with:  
          issue-number: 1347
          body: ${{ env.COMMENT }}
